### ISSUE TITLE
Problem when taking screenshots

### ISSUE THREAD

**Issue by videlalvaro** [manekinekko/ms-moonshot#2]
I want to take the following screenshot:

![good_screenshot](https://user-images.githubusercontent.com/30834/93452339-971b6200-f8d8-11ea-9a79-3bf0b22f5525.png)

But I end up getting this screenshot:

![bad_screenshot](https://user-images.githubusercontent.com/30834/93452344-97b3f880-f8d8-11ea-9030-f2b80a0bc1c0.png)

The problem seems to be with horizontal scrolling, since every new panel in the portal is scrolled horizontally. The extension seems to screenshot the beginning of the horizontal scroll.

I'm on Windows 10 using Edge

**Comment by manekinekko** [comment]
Hey @videlalvaro I fixed this issue in https://github.com/manekinekko/ms-moonshot/commit/ee731bcc1c44264e4643442577780d1727b9529b can you give it a try and let me know?
